import React from "react"
import Head from "next/head"
import Navbar from "./Navbar"
import Header from "./Header"

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Wellston Associates | Licensed Land Surveyors</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <Header />
      <Navbar />
      {children}
    </div>
  )
}

export default Layout
